name: Deployment

on:
  push:
    branches:
      - main
      - canary

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Run tests
      run: |
        pytest tests/

  deploy:
    needs: build
    runs-on: ubuntu-latest

    steps:
    - name: Deploy to Kubernetes
      run: |
        kubectl apply -f infra/k8s/backend-deployment.yaml
        kubectl apply -f infra/k8s/backend-service.yaml
        kubectl apply -f infra/k8s/frontend-deployment.yaml
        kubectl apply -f infra/k8s/frontend-service.yaml
